update outpaint/cases.json
Fix missing extension issue
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\aitools\\Meissonic\\assets\\outpaint\\__G2yFuW7jQjpg'